---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: vikunja-secret
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: "fb4b23d9-fcb4-430d-bbfe-b441006e1963"
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "473c71e1-b13c-4f64-a1a7-b441006dc7aa"
