---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: "${APP}-map"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      bluemap:
        containers:
          app:
            image:
              repository: nginx
              tag: stable-alpine
            ports:
              - containerPort: &port 8080
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: bluemap
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: bluemap
        endpoints:
          - port: http
    route:
      app:
        hostnames:
          - "${APP}.map.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: ${APP}
      config-file:
        type: configMap
        name: nginx-configmap
        globalMounts:
          - path: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true