---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}-map"
spec:
  accessModes: ["ReadWriteOnce}"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-map-dst"
  resources:
    requests:
      storage: "5Gi"
  storageClassName: "ceph-block"