---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermod-gateway-config
data:
  yarp.config: |
    {
      "ReverseProxy": {
        "Routes": {
          "catch-all": {
            "ClusterId": "hermod-api",
            "Match": { "Path": "{**catch-all}" }
          }
        },
        "Clusters": {
          "hermod-api": {
            "Destinations": {
              "destination1": {
                "Address": "http://hermod-api:8080"
              }
            }
          }
        }
      }
    }
