---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: dockerhub-auth
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"https://index.docker.io/v1/":{"username":"{{ .DOCKERHUB_USERNAME }}","password":"{{ .DOCKERHUB_TOKEN }}","auth":"{{ printf "%s:%s" .DOCKERHUB_USERNAME .DOCKERHUB_TOKEN | b64enc }}"}}}
  data:
    - secretKey: DOCKERHUB_USERNAME
      remoteRef:
        key: "11fe4697-3b44-4dd1-bd95-b405007793f0"
    - secretKey: DOCKERHUB_TOKEN
      remoteRef:
        key: "eb833080-b889-494d-b59c-b40500778861"
