---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: frigate-secret
    template:
      data:
        FRIGATE_JWT_SECRET: "{{ .JWT_SECRET }}"
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: "854c763c-ac6b-40cc-ac73-b413002cc1ed"
