---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermod-bot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: hermod-bot-secret
    template:
      data:
        Discord__Token: "{{ .DISCORD_TOKEN }}"
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: "4013098e-ccf2-490d-b45b-b405006d1f23"
