---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hermod-bot
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      hermod-bot:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/theiam79/hermod-bot
              tag: vNext
              pullPolicy: Always
            env:
              TZ: America/Chicago
              BOT_DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: hermod-bot-pg-app
                    key: host
              BOT_DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: hermod-bot-pg-app
                    key: username
              BOT_DB_PASS:
                valueFrom:
                  secretKeyRef:
                    name: hermod-bot-pg-app
                    key: password
              BOT_DB_NAME:
                valueFrom:
                  secretKeyRef:
                    name: hermod-bot-pg-app
                    key: dbname
              ConnectionStrings__bot-db: Host=$(BOT_DB_HOST);Port=5432;Database=$(BOT_DB_NAME);Username=$(BOT_DB_USER);Password=$(BOT_DB_PASS)
              ConnectionStrings__nats: nats://nats.hermod.svc.cluster.local:4222
              WebApp__BaseUrl: https://beta.hermod.dev
              OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector.observability.svc.cluster.local:4318
              OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
              OTEL_SERVICE_NAME: hermod-bot
            envFrom:
              - secretRef:
                  name: hermod-bot-secret
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
    service:
      app:
        controller: hermod-bot
        ports:
          http:
            port: 8080
