---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booksync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: booksync-secret
    template:
      data:
        KEYCLOAK_CLIENT_SECRET: "{{ .KEYCLOAK_CLIENT_SECRET }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        AUTH_SESSION_SECRET: "{{ .AUTH_SESSION_SECRET }}"
  data:
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: "d628e7dd-acbb-4451-bafc-b41501531809"
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: "b4804cf4-cc10-4dc3-b97f-b4150153c1b2"
    - secretKey: AUTH_SESSION_SECRET
      remoteRef:
        key: "2aabcbb7-23ff-45f5-8ca2-b4150153d489"
