---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: actual-secret
    template:
      data:
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "REPLACE-WITH-BWS-SECRET-UUID" # TODO(user): plaintext client secret (digest goes to authelia)
