---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: actual-secret
    template:
      data:
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "dcb1e6c5-883a-4f97-bd1e-b4b1002b6a5d"
