---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./operator/helmrelease.yaml
  - ./operator/ocirepository.yaml
  - ./gpu/helmrelease.yaml
  - ./gpu/ocirepository.yaml
