---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermod-api
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: hermod-api-secret
    template:
      data:
        Discord__ClientId: "{{ .DISCORD_CLIENT_ID }}"
        Discord__ClientSecret: "{{ .DISCORD_CLIENT_SECRET }}"
  data:
    - secretKey: DISCORD_CLIENT_ID
      remoteRef:
        key: "49bfe23e-5189-4183-8c31-b405006c9333"
    - secretKey: DISCORD_CLIENT_SECRET
      remoteRef:
        key: "040baf17-e6d8-483b-9aab-b405006cc1e2"
