---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hermod-api
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      hermod-api:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/theiam79/hermod-api
              tag: vNext
            env:
              TZ: America/Chicago
              ConnectionStrings__hermod-db:
                valueFrom:
                  secretKeyRef:
                    name: hermod-api-pg-app
                    key: uri
              ConnectionStrings__auth-db:
                valueFrom:
                  secretKeyRef:
                    name: hermod-auth-pg-app
                    key: uri
              ConnectionStrings__nats: nats://nats.hermod.svc.cluster.local:4222
              Auth__ExternalBaseUrl: https://beta.hermod.dev
            envFrom:
              - secretRef:
                  name: hermod-api-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /alive
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    service:
      app:
        controller: hermod-api
        ports:
          http:
            port: *port
