---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game-servers
components:
  - ../../components/common
resources:
  - ./abiotic/ks.yaml