---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: akri
spec:
  interval: 10m
  url: https://project-akri.github.io/akri
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akri
spec:
  interval: 1h
  chart:
    spec:
      chart: akri
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: akri
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    webhookConfiguration:
      enabled: false
