---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermod
components:
  - ../../components/common
resources:
  - ./aspire-dashboard/ks.yaml
  - ./hermod-db/ks.yaml
  - ./nats/ks.yaml
  - ./hermod-api/ks.yaml
  - ./hermod-bot/ks.yaml
  - ./hermod-gateway/ks.yaml
