---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "${VOLSYNC_SCHEDULE:=0 */12 * * *}"
  kopia:
    compression: zstd-fastest
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    parallelism: 2
    repository: "${APP}-volsync-secret"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
    accessModes: ["${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    moverVolumes:
      - name: repository
        nfs:
          server: snotra.cluster
          path: /mnt/user/volsync-kopia
    moverVolumeMounts:
      - name: repository
        mountPath: /repository
    retain:
      hourly: 24
      daily: 7
