---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valheim
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: valheim-secret
    template:
      data:
        PASSWORD: "{{ .PASSWORD }}"
        WEBHOOK_URL: "{{ .WEBHOOK_URL }}"
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: "08110651-ccb9-4af3-9406-b4c100247e59"
    - secretKey: WEBHOOK_URL
      remoteRef:
        key: "48f504c3-8836-4e92-a56b-b4c100245d86"
