---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valheim
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: valheim-secret
    template:
      data:
        PASSWORD: "{{ .PASSWORD }}"
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: "00000000-0000-0000-0000-000000000000" # TODO: bws id of VALHEIM_PASSWORD (README)
