---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: github-webhook-token-secret
    template:
      data:
        token: "{{ .FLUX_TOKEN }}"
  data:
  - secretKey: FLUX_TOKEN
    remoteRef:
      key: "b8d30c3c-a818-45ae-abf0-b301005594b1"