---
settings:
  bwSecretsManagerRefreshInterval: 300
  cloudRegion: US
  replicas: 1
# Settings specific to the pod containers
containers:
  manager:
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.14.1
    # The pod resource requirements.  You can adjust these up and down for your environment
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  # Provide annotations for the service account
  serviceAccount:
    annotations: {}
# Service endpoint configuration for the metrics service.
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP