---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: abs-agg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: abs-agg-secret
    template:
      data:
        HARDCOVER_TOKEN: "{{ .HARDCOVER_TOKEN }}"
  data:
    - secretKey: HARDCOVER_TOKEN
      remoteRef:
        key: "4afc1d45-4e0f-4463-8723-b4040091015b"
