---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: file-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      file-server:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: nginx
              tag: latest
            ports:
              - containerPort: &port 80
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1024Mi
    service:
      app:
        controller: file-server
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: file-server
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config-file:
        type: configMap
        name: nginx-configmap
        globalMounts:
          - path: /etc/nginx/nginx.conf
            subPath: config.yaml
            readOnly: true