---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: qbittorrent-secret
    template:
      data:
        MOUSEHOLE_AUTH_PASSWORD: "{{ .MOUSEHOLE_AUTH_PASSWORD }}"
  data:
    - secretKey: MOUSEHOLE_AUTH_PASSWORD
      remoteRef:
        key: "fb1279f4-6280-4e21-83c0-b462000ee6b5"
