---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: recyclarr-secret
    template:
      data:
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR4K_API_KEY: "{{ .SONARR4K_API_KEY }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR4K_API_KEY: "{{ .RADARR4K_API_KEY }}"
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: "064f8557-01a2-4374-a5ae-b40a008bdd39"
    - secretKey: SONARR4K_API_KEY
      remoteRef:
        key: "fa4b471e-6c34-46fe-9ef7-b40a008b74ef"
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: "287d134a-6820-471f-9c7d-b40a008b8044"
    - secretKey: RADARR4K_API_KEY
      remoteRef:
        key: "875cfc05-309d-4246-a3ea-b40a008b8eaf"
