---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
components:
  - ../../components/common
  - ../../components/volsync
resources:
  - ./mc-router/ks.yaml
  - ./servers/ks.yaml