---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multi-scrobbler
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: multi-scrobbler-secret
    template:
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        LZ_TOKEN: "{{ .LZ_TOKEN }}"
        LZ_USER: "{{ .LZ_USER }}"
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: "61f96551-be3e-4568-a129-b40e0090b492"
    - secretKey: LZ_TOKEN
      remoteRef:
        key: "0a5def3a-93ce-4a01-84b9-b40e00917cb4"
    - secretKey: LZ_USER
      remoteRef:
        key: "d220b555-8ba7-4a07-a423-b40e0091872f"
