---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: abiotic
spec:
  driftDetection:
    mode: enabled
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      abiotic:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/pleut/abiotic-factor-linux-docker
              tag: latest
            env:
              - name: MaxServerPlayers
                value: 6
              - name: Port
                value: &port 7777
              - name: QueryPort
                value: &query 27015
              - name: ServerPassword
                valueFrom:
                  secretKeyRef:
                    name: abiotic-secret
                    key: SERVER_PASSWORD
              - name: SteamServerName
                value: "Tired Old Scientists"
              - name: UsePerfThreads
                value: true
              - name: NoAsyncLoadingThread
                value: true
              - name: WorldSaveName
                value: "Cascade"
              # AutoUpdate: false
              # AdditionalArgs: -SandboxIniPath=Config/WindowsServer/ServerSandbox.ini
            resources:
              requests:
                cpu: 512m
                memory:  4000Mi
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: abiotic
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ${APP}.${SECRET_DOMAIN}
        loadBalancerIP: 192.168.100.18
        ports:
          game:
            protocol: UDP
            port: *port
            targetPort: *port
          query:
            port: *query
            targetPort: *query
    # route:
    #   app:
    #     hostnames:
    #       - "${APP}.${SECRET_DOMAIN}"
    #     parentRefs:
    #       - name: internal
    #         namespace: kube-system
    #         sectionName: https
    #     rules:
    #       - backendRefs:
    #           - identifier: app
    #             port: *port
    persistence:
      data:
        existingClaim: ${APP}
        globalMounts:
          - path: /server/AbioticFactor/Saved
      server:
        existingClaim: abiotic-server-files
        globalMounts:
          - path: /server
      # local:
      #   type: emptyDir
      #   globalMounts:
      #     - path: /.local
      # steam:
      #   type: emptyDir
      #   globalMounts:
      #     - path: /.steam
      # wine:
      #   type: emptyDir
      #   globalMounts:
      #     - path: /.wine