---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abiotic-server-files
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block