---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: kometa-secret
    template:
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: "61f96551-be3e-4568-a129-b40e0090b492"
