---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vikunja-pg
  namespace: &namespace default
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: cloudnative-pg-barman-cloud
      namespace: database
    - name: external-secrets
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/default/vikunja/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vikunja
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/external
    - ../../../../components/volsync
  dependsOn:
    - name: vikunja-pg
      namespace: default
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/default/vikunja/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: tasks
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
