---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  chartRef:
    kind: OCIRepository
    name: spegel
  interval: 1h
  values:
    spegel:
      containerdSock: /run/containerd/containerd.sock
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true