endpoints:
  - name: "${APP}"
    group: guarded
    url: 1.1.1.1
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.${SECRET_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"