---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: slskd-secret
    template:
      data:
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
        SLSKD_SLSK_LISTEN_PORT: "{{ .SLSKD_FORWARDED_PORT }}"
  data:
    - secretKey: SLSKD_SLSK_USERNAME
      remoteRef:
        key: "cce3dd16-4e35-473c-8e13-b40e008054d2"
    - secretKey: SLSKD_SLSK_PASSWORD
      remoteRef:
        key: "723c5199-84fb-4022-b64a-b40e0080409e"
    - secretKey: SLSKD_FORWARDED_PORT
      remoteRef:
        key: "8e09db50-dfcf-418e-a70e-b40e00817655"
