---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: slskd-secret
    template:
      data:
        VPN_SERVICE_PROVIDER: airvpn
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_PRESHARED_KEY: "{{ .WIREGUARD_PRESHARED_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        SERVER_COUNTRIES: "{{ .SERVER_COUNTRIES }}"
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
        FIREWALL_VPN_INPUT_PORTS: "{{ .SLSKD_FORWARDED_PORT }}"
        SLSKD_SLSK_LISTEN_PORT: "{{ .SLSKD_FORWARDED_PORT }}"
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: "8d965a4a-42e2-4216-b409-b40e007f9996"
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: "264a949e-b947-41a3-995c-b40e007fb7de"
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: "17d891ff-36fd-488e-8cbd-b40e007fd6bc"
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: "290f6e84-f4ef-41a2-bdfd-b40e0080056a"
    - secretKey: SLSKD_SLSK_USERNAME
      remoteRef:
        key: "cce3dd16-4e35-473c-8e13-b40e008054d2"
    - secretKey: SLSKD_SLSK_PASSWORD
      remoteRef:
        key: "723c5199-84fb-4022-b64a-b40e0080409e"
    - secretKey: SLSKD_FORWARDED_PORT
      remoteRef:
        key: "8e09db50-dfcf-418e-a70e-b40e00817655"
