---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tempo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.21.0
  url: oci://ghcr.io/grafana/helm-charts/tempo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tempo
  values:
    tempo:
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
      retention: 168h
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
    persistence:
      enabled: true
      storageClassName: ceph-block
      size: 20Gi
