---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: home-assistant-secret
    template:
      data:
        # Used by the code-server sidecar (--auth password)
        PASSWORD: "{{ .CODE_SERVER_PASSWORD }}"
  data:
    - secretKey: CODE_SERVER_PASSWORD
      remoteRef:
        key: "ab9dc34a-3bcb-487d-a2f7-b45f000c6f6d"
