---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: unifi-secret
    template:
      data:
        MONGO_USER: unifi
        MONGO_PASS: "{{ .MONGO_PASS }}"
  data:
    - secretKey: MONGO_PASS
      remoteRef:
        key: "4ad7eda1-383e-46ff-92c1-b4ab00396220"
