---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mealie-secret
    template:
      data:
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OPENAI_API_KEY: "{{ .GEMINI_API_KEY }}"
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "b46ade82-2ca1-4d42-ac8b-b465006c3f4d"
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: "efd82ea3-60fa-40bf-9642-b465006d6725"
