---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mealie-secret
    template:
      data:
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OPENAI_API_KEY: "{{ .GEMINI_API_KEY }}"
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "PLACEHOLDER-MEALIE-OIDC-CLIENT-SECRET-UUID"
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: "PLACEHOLDER-GEMINI-API-KEY-UUID"
