---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tunarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      tunarr:
        containers:
          app:
            image:
              repository: ghcr.io/chrisbenincasa/tunarr
              tag: v1.2.8
            env:
              TZ: America/Chicago
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
                gpu.intel.com/i915: "1"
              limits:
                memory: 4Gi
                gpu.intel.com/i915: "1"
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 105
    service:
      app:
        controller: tunarr
        ports:
          http:
            primary: true
            port: *port
    route:
      app:
        hostnames:
          - "tunarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: tunarr
        globalMounts:
          - path: /config/tunarr
      media:
        type: nfs
        server: snotra.internal
        path: /mnt/user/media
        globalMounts:
          - path: /data/media
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
