---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hermod-api
  namespace: &namespace hermod
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: hermod-db
      namespace: hermod
    - name: hermod-nats
      namespace: hermod
    - name: external-secrets
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/hermod/hermod-api/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
