---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mc-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mc-users-secret
    template:
      data:
        OPS: "{{ .OPS }}"
        WHITELIST: "{{ .WHITELIST }}"
  data:
  - secretKey: OPS
    remoteRef:
      key: "970d1a32-294c-4e03-a695-b302007965bb"
  - secretKey: WHITELIST
    remoteRef:
      key: "730bba04-5fc5-4d9d-96ef-b302007a19fc"